# Generated by Django 4.0.2 on 2022-03-05 14:26

from django.db import migrations


def create_groups(apps, schema_editor):
    from django.contrib.auth.models import Group

    Group.objects.create(name='students')


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]