# Generated by Django 4.0.2 on 2022-03-05 14:26
import os

from django.db import migrations


def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model
    User = get_user_model()

    DJANGO_SU_NAME = os.environ.get('DJANGO_SU_NAME')
    DJANGO_SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL')
    DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD')

    User.objects.create_superuser(
        fullname=DJANGO_SU_NAME,
        email=DJANGO_SU_EMAIL,
        password=DJANGO_SU_PASSWORD,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_groups'),
    ]

    operations = [
        migrations.RunPython(generate_superuser)
    ]