services:
  backend:
    build:
      context: ./app
    ports:
      - "8000:8000"
    restart: 'on-failure'
    volumes:
      - ./app:/app
    env_file:
      - './app/env/.env'
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - './app/env/.env'
volumes:
  postgres: